// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("http://10.0.2.8/sdkDl/login.php")
    await driver.findElement(By.id("sys_lg")).click()
    await driver.findElement(By.id("sys_lg")).sendKeys("6045dad5c832dc3a")
    await driver.findElement(By.name("sys_pw")).click()
    await driver.findElement(By.name("sys_pw")).sendKeys("mapfansdk")
    await driver.findElement(By.linkText("ログイン")).click()
    await driver.sleep(5000ms)
    await driver.findElement(By.linkText("ログアウト")).click()
  })
})
